# Generated by Django 2.2.9 on 2020-01-08 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fechas',
            field=models.ManyToManyField(blank=True, to='base.Fecha'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ramos',
            field=models.ManyToManyField(blank=True, to='base.Ramo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
